### ISSUE TITLE
Crash when right clicked with iron in hand and drawer key in off hand

### ISSUE THREAD

**Issue by quasarea** [TheCBProject/Translocators#59]
In Project Ozone 3 3.0.37, right clicking on item translocation with iron ingots in hand and drawer key in off hand crashed the game totally - now start will fail with:

    [22:34:48] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
    net.minecraft.util.ReportedException: Ticking block entity
            at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:773) ~[MinecraftServer.class:?]
            at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) ~[nz.class:?]
            at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) ~[MinecraftServer.class:?]
            at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
            at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
    Caused by: java.lang.NullPointerException
            at codechicken.translocators.part.ItemTranslocatorPart.func_73660_a(ItemTranslocatorPart.java:154) ~[ItemTranslocatorPart.class:?]
            at codechicken.multipart.scalatraits.TTickableTile$class.update(TTickableTile.scala:58) ~[TTickableTile$class.class:?]
            at codechicken.multipart.scalatraits.JTickableTile$class.func_73660_a(TTickableTile.scala:95) ~[?:?]
            at TileMultipart_cmp$$0.func_73660_a(Unknown Source) ~[?:?]
            at net.minecraft.world.World.func_72939_s(World.java:1835) ~[amu.class:?]
            at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) ~[oo.class:?]
            at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) ~[MinecraftServer.class:?]
            ... 4 more
    [22:34:48] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: E:\PO3-Server-3.0.37\.\crash-reports\crash-2019-02-07_22.34.48-server.txt

[crash-2019-02-07_22.34.48-server.txt](https://github.com/TheCBProject/Translocators/files/2842931/crash-2019-02-07_22.34.48-server.txt)

**Comment by Naxanria** [comment]
This also works with just an empty offhand.

See also https://github.com/FTBTeam/FTB-Sky-Odyssey/issues/312

**Comment by jezzen** [comment]
Just had a similar crash. Tried adding iron ingot to a translocator on a drawer system. In my case there were no drawers connected so null pointer would come from there being no valid inventories detected. Not sure if your situation was the same.

**Comment by Gunner76th** [comment]
[crash-2019-06-11_21.14.37-server.txt](https://github.com/TheCBProject/Translocators/files/3279295/crash-2019-06-11_21.14.37-server.txt)

Just had this crash while running Sky Factory 4. Player was attempting to upgrade and configure the translocator.
